// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package main

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// @counts(global, session)
func homepage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><title>Go + Templ + HTMX Example</title><script src=\"https://unpkg.com/htmx.org@1.8.4\"></script></head><body><h1>Go + Templ + HTMX Example</h1><button hx-get=\"/button-click\" hx-target=\"#result\">Click Me</button> <a href=\"/Settings\"><button>Settings</button></a><div id=\"result\">Hello!</div><div><form hx-post=\"/addRow\" hx-target=\"#addRowConfirm\" hx-swap=\"innerHTML\"><label for=\"url\">Enter URL:</label> <input type=\"text\" id=\"url\" name=\"url\" required> <button type=\"submit\">Add Row</button></form><div id=\"addRowConfirm\"></div></div><div><button hx-get=\"/tableHandler\" hx-trigger=\"click\" hx-target=\"#table-body\">Load Data</button><table border=\"1\"><thead><tr><th>ID</th><th>URL</th></tr></thead> <tbody id=\"table-body\"><!-- Dynamic content will be loaded here --></tbody></table></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
